### PR TITLE
feat(storage): add chrome policy support

### PR DESCRIPTION
**Pull request by Silthus**
Adds #43 

I added the option to load settings from the storage.managed api. This enabled companies to provide the initial settings of the plugin via GPOs or registry.

### CODE REVIEW

**Comment by CorCornelisse** [comment]
Hi @KevinSheedy, do you have an opportunity or are you planning to merge the above request? We're looking forward to using "chrome-tab-rotate", however currently we can't use it due to the lack of "GPO support, this merge request looks like it adds the missing support we need.

**Comment by Silthus** [comment]
Hi @corconelisse you are in luck :)
The last few weeks I re-coded the tab-rotate plugin in Typescript implementing policy support from the beginning. I will publish the extension to the chrome web store in the next few days. All that is left todo is some documentation.

Keep an eye out on my repository and blog for more information about the launch of the extension: https://github.com/Silthus/chrome-enterprise-tab-rotate

**Comment by CorCornelisse** [comment]
Hi @Silthus that's terrific news! Would you happen to have a "hidden" chrome extension url available where we can run some tests with it leading up to your chrome web store release?

**Comment by Silthus** [comment]
I will create an automated build process with an artifact for testing tomorrow.
I am just curious: will you use the remote Config url feature or are you interested in providing the complete config via policy?

Currently my rework only supports using a remote JSON config, e.g. hosted in a git repo or webserver.

**Comment by CorCornelisse** [comment]
We are mainly interested in providing the complete config via the policy
option, we've managed chromebits, so the policy config option would be the
easiest to manage for us.

**Comment by Silthus** [comment]
@CorCornelisse can you take a look at the following? If your tests are successful I will merge and publish to the chrome store.
https://github.com/Silthus/chrome-enterprise-tab-rotate/pull/3

**Pull request closed without merging**
